### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### fog/fog-aws now has a Chat Room on Gitter

@lanej has just created a chat room. You can visit it here: [https://gitter.im/fog/fog-aws](https://gitter.im/fog/fog-aws?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/fog/fog-aws?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by lanej** [comment]
@fog/fog-aws i was just peeking around at this.  not sure if it's something we want to embrace.

**Comment by geemus** [comment]
I believe @fog/fog-openstack uses it, maybe they can chime in on what they think?

**Comment by jjasghar** [comment]
Honestly, I don't really check Gitter, i have a billion other chat programs, and unless someone mentions me, Gitter isn't even on my radar.

**Comment by Ladas** [comment]
I do use gitter. And I got email notifications if somebody needs something, so it's quite handy :-)

**Comment by lanej** [comment]
I've been using it for some other projects.  I get emails when there are outstanding notifications and chatting with people seemingly cuts down github noise.

**Comment by lanej** [comment]
I'm going to close this.  ATM I'd prefer to keep communication consolidated in one place.

**Pull request closed without merging**
