### PR TITLE
Fix multipart upload

### PR DESCRIPTION
**Pull request by nobmurakita**
Add missing 'self' to call setter method

### CODE REVIEW

**Comment by geemus** [comment]
I think the self should be implied there, and I don't believe I've heard about any related issues. Were you having a particular error that this fixes? Just trying to make sure I understand the context. Thanks!

**Comment by nobmurakita** [comment]
If `self` is missing, the local variable `multipart_chunk_size` is created and can't access `@multipart_chunk_size`.
When body size is smaller than 5 GB, `multipart_chunk_size` on the following code is `nil`.
Multipart upload doesn't work even if `@multipart_chunk_size` is set.

```
if multipart_chunk_size && Fog::Storage.get_body_size(body) >= multipart_chunk_size && body.respond_to?(:read)
  data = multipart_save(options)
  merge_attributes(data.body)
else
```

**Comment by lanej** [comment]
Small verification of @nobmurakita's claim.

```ruby
Class.new do
  attr_accessor :foo
  def bar
       foo = 'bar'
    end
end.new.tap { |x| x.bar }.foo == 'bar' # false
```

@geemus The issue and the fix are valid but I'll leave it you to confirm.

**Comment by geemus** [comment]
@nobmurakita thanks for the clarification.

@lanej thanks for the verification.

**Pull request merged**
