### PR TITLE
Fixed some missing parts in change sets

### PR DESCRIPTION
**Pull request by nilroy**
This PR solves the following:
1. Get the status of cloudformation change set creation
2. Create change set for stacks that changes IAM roles/policies

### CODE REVIEW

**Comment by nilroy** [comment]
@lanej @geemus Its a very small PR..Please review

**Comment by nilroy** [comment]
It seems I need to push some more changes to this PR...Don't merge it yet

**Comment by nilroy** [comment]
@geemus This PR is ready. It's pretty straightforward

**Comment by geemus** [comment]
LGTM, will leave for @lanej to double-check and merge.

**Comment by lanej** [comment]
Thanks @nilroy.

**Comment by nilroy** [comment]
@lanej thanks a lot. When can we expect the new gem version?

**Comment by lanej** [comment]
https://rubygems.org/gems/fog-aws/versions/0.13.0

**Comment by nilroy** [comment]
@lanej Thanks a lot

**Pull request merged**
