### PR TITLE
Migrate Service mapper from Fog

### LINKED ISSUE #390: Missing file for extraction?
There is one file at [`fog`](https://github.com/fog/fog/blob/master/lib/fog/aws/service_mapper.rb) that is related to `aws`. Should we move it here or is it only related to the `fog` context?

### PR DESCRIPTION
**Pull request by plribeiro3000**
closes #390

### CODE REVIEW

**Comment by plribeiro3000** [comment]
It's been a while i don't follow the AWS portion of `fog` anymore so i'm kind of lost on some points. 😄 

While running the tests i've noticed there are some noisy puts. Are those supposed to be there?
If not i can make another PR removing them.

I've noticed also that the file [`CONTRIBUTORS`](https://github.com/fog/fog-aws/blob/master/CONTRIBUTORS.md) is kind of outdated. Should i send another PR for that also?

Also, how is `CHANGELOG` being updated? should i add something?

cc @lanej @geemus

**Comment by lanej** [comment]
> While running the tests i've noticed there are some noisy puts. Are those supposed to be there?
If not i can make another PR removing them.

That would be great.

> I've noticed also that the file CONTRIBUTORS is kind of outdated. Should i send another PR for that also?

Yes please.

> Also, how is CHANGELOG being updated? should i add something?

I've been using https://github.com/skywinder/github-changelog-generator to update the CHANGELOG automatically.

**Comment by plribeiro3000** [comment]
@lanej Working on those PR's.

Is there something else missing here? Dunno if the broken build is related. =s

**Comment by plribeiro3000** [comment]
@lanej See #393 and #394

**Comment by plribeiro3000** [comment]
Also, regarding the `CHANGELOG` i think that's just great!

I prefer to follow [`keepachangelog`](http://keepachangelog.com/en/1.0.0/) and keep it more human readable. Just dropping this here in case you find it interesting. =)

**Comment by geemus** [comment]
I use `osrcry` to update contributors on things usually, fwiw. (it has stuff for updating license too, maybe even contributing). I made it a while back to help automate, since I seem to have a growing set of OS things to try and keep straight. I'd welcome feedback on improving it, but hope it can streamline some of this for us.

**Comment by geemus** [comment]
Here is `osrcry` link: https://github.com/geemus/osrcry

It's also a gem with a binary (which is how I actually use it).

**Pull request merged**
