### PR TITLE
Docs: Update changelog for 3.0.0

### PR DESCRIPTION
**Pull request by jaredbeck**
Congrats on the 3.0.0 release!

I tried to organize this changelog entry to make upgrading easier for users. I think that's the main purpose of a changelog. E.g. I'm upgrading and I want to know what changed. Usually, I don't care what was added or fixed, I just want to know if there are breaking changes. I hope you like this format, it's worked really well for me on my projects.

### CODE REVIEW

**Comment by geemus** [comment]
Seems fine to me, defer to @lanej for merge though.

**Comment by jaredbeck** [comment]
Two week ping. Please review.

**Comment by jaredbeck** [comment]
Two month ping, please review. Just docs, should be quick review.

**Comment by geemus** [comment]
Bringing this in (though I'm still worried it will get wiped out with scripts later). Sorry for the delays.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
