### PR TITLE
Add support for encrypted snapshots

### PR DESCRIPTION
**Pull request by gswallow**
The default CMK for EBS is used

### CODE REVIEW

**Comment by geemus** [comment]
Anything we can assist with here?

**Comment by gswallow** [comment]
I just asked on IRC :)

**Comment by gswallow** [comment]
Yes, I'm stumped.

I'm trying to extend fog to copy encrypted snapshots.  I've thrown just
about everything I can find at it, but each copy-snapshot operation fails.
I don't think I'm submitting a presigned URL corrrectly?

My feeble attempt is here: https://github.com/gswallow/fog-aws.

**Comment by geemus** [comment]
Possibly, I'm not really familiar with the specifics around encrypted stuff here.

@lanej do you have any experience or advice to offer?

@fcheung any thoughts on presigned URL formatting issues here?

**Comment by fcheung** [comment]
How does it fail? The documentation about what the presigned url should be seems pretty vague. Could the issue be that this code will generate a signed url where the host is the s3 endpoint for this region whereas what is required is a signed url where the host is the ec2 endpoint?

**Comment by gswallow** [comment]
I took a crack at copying an encrypted snapshot here:

https://github.com/gswallow/fog-aws/commit/9e13310b5170ebe335c76678ab535c918b602659

I suspect that using ::Fog::Storage.signed_url is wrong, but it's the example of using a v4 signature I could find, after following some glacier threads a while ago.

Copy snapshot request: 

excon.request
  :body                => "Action=CopySnapshot&Description=Copy%20of%20snap-02b7bf6b%20from%20us-east-1%20backup_id%2020150819.11&Encrypted=true&KmsKeyId=arn%3Aaws%3Akms%3Aus-west-
2%3Amyaccountid%3Akey%2Fsome-key&PresignedUrl=https%3A%2F%2Fs3.amazonaws.com%2F%3FAction%3DCopySnapshot%26SourceRegion%3Dus-east-1%26SourceSnapshotId%3Dsnap-02b7bf6b%26DestinationRegion%3Dus-west-2%26X-Amz-Expires%3D3600%26X-Amz-Date%3D20150819T134217Z%26X-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3Daccess-key%2F20150819%2Fus-east-1%2Fs3%2Faws4_request%26X-Amz-SignedHeaders%3Dhost%26X-Amz-Signature%3some-kind-of-signature&SourceRegion=us-east-1&SourceSnapshotId=snap-02b7bf6b&Version=2015-04-15"
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :expects             => 200
  :headers             => {
    "Authorization" => "REDACTED"
    "Content-Type"  => "application/x-www-form-urlencoded"
    "Host"          => "ec2.us-west-2.amazonaws.com"
    "User-Agent"    => "fog/1.33.0 fog-core/1.32.1"
    "x-amz-date"    => "20150819T134217Z"
  }
  :host                => "ec2.us-west-2.amazonaws.com"
  :hostname            => "ec2.us-west-2.amazonaws.com"
  :idempotent          => nil
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "POST"
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/"
  :persistent          => false
  :port                => 443
  :query               => nil
  :read_timeout        => 60
  :response_block      => #<Proc:0x007fa97a2b4c08@/Users/gswallow/.rvm/gems/ruby-2.2.0@cfn/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:29 (lambda)>
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :versions            => "excon/0.45.4 (x86_64-darwin14) ruby/2.2.0"
  :write_timeout       => 60

Response:

excon.response
  :body          => ""
  :headers       => {
    "Content-Type" => "text/xml;charset=UTF-8"
    "Date"         => "Wed, 19 Aug 2015 13:42:14 GMT"
    "Server"       => "AmazonEC2"
    "Vary"         => "Accept-Encoding"
  }
  :local_address => "10.10.0.75"
  :local_port    => 64286
  :reason_phrase => "OK"
  :remote_ip     => "54.240.251.0"
  :status        => 200
  :status_line   => "HTTP/1.1 200 OK\r\n"

Describe snapshots request:

excon.request
  :body                => "Action=DescribeSnapshots&Filter.1.Name=snapshot-id&Filter.1.Value.1=snap-c8ee874e&RestorableBy=self&Version=2015-04-15"
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :expects             => 200
  :headers             => {
    "Authorization" => "REDACTED"
    "Content-Type"  => "application/x-www-form-urlencoded"
    "Host"          => "ec2.us-west-2.amazonaws.com"
    "User-Agent"    => "fog/1.33.0 fog-core/1.32.1"
    "x-amz-date"    => "20150819T134218Z"
  }
  :host                => "ec2.us-west-2.amazonaws.com"
  :hostname            => "ec2.us-west-2.amazonaws.com"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "POST"
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/"
  :persistent          => false
  :port                => 443
  :query               => nil
  :read_timeout        => 60
  :response_block      => #<Proc:0x007fa97a264d98@/Users/gswallow/.rvm/gems/ruby-2.2.0@cfn/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:29 (lambda)>
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :versions            => "excon/0.45.4 (x86_64-darwin14) ruby/2.2.0"
  :write_timeout       => 60

Contents of response block (which aren't in the excon debug output): 

DEBUG: {"tagSet"=>{}, "snapshotId"=>"snap-c8ee874e", "volumeId"=>"vol-10d69a6b", "status"=>"pending", "startTime"=>2015-08-19 13:42:14 UTC, "progress"=>"0%", "ownerId"=>"294091367658", "volumeSize"=>0, "description"=>"Copy of snap-02b7bf6b from us-east-1 backup_id 20150819.11", "encrypted"=>false}

**Pull request closed without merging**
