### PR TITLE
Add support for EC2 Container Service

### PR DESCRIPTION
**Pull request by nomadium**
This implements Amazon EC2 Container Service support for fog.

### CODE REVIEW

**Comment by nomadium** [comment]
I'm also providing some scripts to verify this works OK. I took the task definition and service demos provided in AWS documentation and uploaded them with my scripts to a gist: https://gist.github.com/nomadium/afd6fb412a2b41ff6ecc.

**Comment by geemus** [comment]
Looks like there are some related test failures, could you dig in there? Just let me know if you have questions or anything I can help with. Thanks!

**Comment by nomadium** [comment]
Hi @geemus, yep I'm reviewing those issues during this week. I'll ping you again when I fix all Travis failures. Thanks!

**Comment by geemus** [comment]
Great, thanks for the update. Just let me know if you have any questions or
anything I can help with. Thanks!

**Comment by nomadium** [comment]
@geemus Hi! I think I'm going to need help with this PR. I having problems with some mocks and tests, sometimes they succeed and sometimes one or more of them fail. I don't know if I'm running into a race condition or something. I implemented them in similar way to another Fog mocks, (i.e. I prepare a valid response for any given request and I save any needed object in ```self.data``` to be used for subsequent requests).

I noticed that for some failed mocked requests if I catch exceptions and retry, some of them succeed but this smells like a hack and doesn't work on all cases.

I'm kinda lost about debugging this, any recommendation?

**Comment by nomadium** [comment]
For example, I simplified mocks for cluster related requests and from time to time one test keep failing. https://github.com/nomadium/fog-aws/blob/de3602954b5dff370f8b410227f83dd80c6f9be6/tests/requests/ecs/cluster_tests.rb#L90 implemented at https://github.com/nomadium/fog-aws/blob/de3602954b5dff370f8b410227f83dd80c6f9be6/lib/fog/aws/requests/ecs/delete_cluster.rb#L40.

**Comment by nomadium** [comment]
I finally saw my mistake with ```delete_cluster``` tests and that gave me a clue about some how to fix the rest of the failing tests. I'll debug them and I'll come back later.

**Comment by nomadium** [comment]
@geemus I finally got the tests passing so you can review the code whenever you want. Thanks!

**Comment by hosh** [comment]
@nomadium I've been using your branch of the code, and it's helped a ton. Thanks for putting this together! :+1:

**Comment by geemus** [comment]
Awesome, travelling this week for work, so falling behind a bit on review tasks, but hope to get back to this soon.

**Comment by geemus** [comment]
Apologies again for delays, looks great, thanks!

**Comment by nomadium** [comment]
@geemus Awesome, thank you for reviewing it and merging it.

**Pull request merged**
