### PR TITLE
ECS container credentials

### PR DESCRIPTION
**Pull request by ryansch**
This adds support for ECS task container credentials/roles.
Docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
aws-sdk PR: https://github.com/aws/aws-sdk-ruby/pull/1243

I used the same algorithm as aws-sdk for choosing when to use the ECS creds.  I don't love the `options[:metadata_connection]` but we have to connect to a different host to get the region when using ECS creds.

### CODE REVIEW

**Comment by lanej** [comment]
This seems pretty straight forward to me.  @geemus mind giving it a look ?

**Comment by geemus** [comment]
👍  Thanks!

**Comment by ryansch** [comment]
@geemus Any chance you could cut a release with these changes?

**Comment by geemus** [comment]
@ryansch probably, but mostly I've been deferring to @lanej for releases. @lanej ?

**Comment by lanej** [comment]
https://rubygems.org/gems/fog-aws/versions/0.11.0

**Comment by geemus** [comment]
Thanks!

**Comment by ryansch** [comment]
Thanks! :tada:

**Pull request merged**
