### PR TITLE
Handle multiple versions of objects in multiple delete request

### PR DESCRIPTION
**Pull request by shanu-idrive**
This PR is fix for issue describe in #598 . Now bulk/multiple delete can handle multiple versions of single object as well in delete 
request. The solution is as discussed in the issue where options hash accepts versions as an array of strings for a object. The PR is backward compatible to support hash with versions as string only.

Thanks for your time.

### CODE REVIEW

**Review by geemus — APPROVED** [review]
Looks good, thanks for taking time to talk and work through this with me.

**Comment by geemus** [comment]
@shanu-idrive Do you need a release with this?

**Comment by shanu-idrive** [comment]
> @shanu-idrive Do you need a release with this?

@geemus thanks for you time for reviewing and approving the changes. Yes I would need a release as we are using this API in our product.

**Comment by jgigault** [comment]
That's awesome! Thanks for this improvement

**Comment by geemus** [comment]
Sounds good. I'll try to release tomorrow (don't want to do it on the weekend when I'm not around/available as much, just in case something goes wrong).

**Comment by shanu-idrive** [comment]
> Sounds good. I'll try to release tomorrow (don't want to do it on the weekend when I'm not around/available as much, just in case something goes wrong).

Sure, as per your convenience.

**Comment by geemus** [comment]
Should now be available as part of v3.10.0. Thanks!

**Pull request merged**
