### PR TITLE
Add log warning message about when not on us-region

### PR DESCRIPTION
**Pull request by kitofr**
- Non us-regions are not supported for mocks. Added message

### CODE REVIEW

**Comment by geemus** [comment]
The error raised here is intended to be inline with the behavior you would see in live usage (I think). Maybe it would be better to use Fog.warning and leave the error unchanged? What do you think?

**Comment by kitofr** [comment]
That sounds like a fair solution. I merely wanted to get some heads up about the region problem whilst using Mocks.
I'll see if I can change it to use `Fog.warning` instead.

**Comment by geemus** [comment]
Sounds good, thanks!

**Comment by lanej** [comment]
@kitofr please rebase off of master

**Comment by kitofr** [comment]
Well... this is over a year old. I you guys want to improve your code, please fix this. I'll leave it up to you.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
