### PR TITLE
Canada and London regions

### PR DESCRIPTION
**Pull request by mattheworiordan**
@geemus this supersedes @chanakyacool PR https://github.com/fog/fog-aws/pull/331 with the us-east-2 back in and less cruft i.e. just the two commits needed.

### CODE REVIEW

**Comment by lanej** [comment]
Thanks @mattheworiordan

**Comment by geemus** [comment]
Thanks!

**Comment by chanakyad-cuelogic** [comment]
thanks @mattheworiordan, @lanej  and @geemus

**Comment by chanakyad-cuelogic** [comment]
@geemus @lanej , would you be updating the version number ?

**Comment by lanej** [comment]
@chanakyad-cuelogic available in https://rubygems.org/gems/fog-aws/versions/1.1.0

**Comment by chanakyad-cuelogic** [comment]
@lanej thanks ... 😊

**Pull request merged**
