### PR TITLE
feat(CONTRIBUTORS): Update

### PR DESCRIPTION
**Pull request by plribeiro3000**
Just a plan `git log --pretty="* %cn <%ce>" | sort | uniq`

cc/ @lanej

### CODE REVIEW

**Comment by lanej** [comment]
thanks @plribeiro3000

**Comment by lanej** [comment]
Looks like `fog-core` `HEAD` is causing everyone's build to fail

**Comment by geemus** [comment]
Seems bad, I'm not sure why it is failing like that though. Any insights?

**Comment by plribeiro3000** [comment]
Merging since is just the `CONTRIBUTORS` file updated. Not related to the broken build.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
