### PR TITLE
Fix blank content-encoding when none is supplied

### PR DESCRIPTION
**Pull request by fcheung**
Should help with fog/fog#3450

### CODE REVIEW

**Comment by lautis** [comment]
With this the Content-Encoding header is set as

```
Content-Encoding:  identity
```

Note that there is two spaces between colon and identity. I'm not sure if that could have any effect.

**Comment by fcheung** [comment]
Not according to http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

**Comment by geemus** [comment]
@fcheung - seems good. Have you confirmed that it helps on #3450? Figure knowing that will make it clearer if we should pull it in or not. Thanks!

**Comment by fcheung** [comment]
@geemus waiting for feedback

**Comment by geemus** [comment]
@fcheung Thanks, that was my impression, just double checking.

**Comment by fcheung** [comment]
@geemus I think we're good to go on this

**Comment by geemus** [comment]
@fcheung thanks, bringing it in.

**Comment by jonbuda** [comment]
Just to follow up on this, it appears as though 'Identity' should not be used for 'Content-Encoding', according to: http://tools.ietf.org/html/rfc2616#section-3.5

Thoughts? I'm not entirely what effect it has on things though, if it is present.

**Comment by wizjo** [comment]
We are experiencing a problem with this fix -- all the gzip files ended up with an empty `Content-Encoding` file header in S3. As a result, our CDN service couldn't determine the actual `Content-Encoding` and is serving assets in their original size. We reverted the change in our fork of gem "fog-aws" and are using that fork, but are there any plans to fix this issue down the road?

**Comment by fcheung** [comment]
So you suffer from the opposite problem than the person that reported the original issue? If identity is an incorrect content encoding (which it seems it is) then we need to figure out what was causing the blank content encoding previously. I suppose it could happen if the content-encoding was explicitly set to an empty string, but not sure how that would happen

**Comment by wizjo** [comment]
@fcheung , this particular fix: https://github.com/fog/fog-aws/blob/9b9faf6818ab27a335cbc0b9675a654ef80124c9/lib/fog/aws/storage.rb#L567 results in a blank "Content-Encoding" file header in S3, which is causing the CDN problem described above.
screen shot 2015-05-06 at 4 20 13 pm

**Comment by fcheung** [comment]
I've created a pull request that changes it back and improves some of the handling, but the original fog issue was by someone having this issue *before* we made this change, so I am not confident this won't introduce a regression

**Comment by geemus** [comment]
I've merged the change, could people who have experienced issues (or are now) try with master and see if it improves their situations? Thanks!

**Pull request merged**
