### PR TITLE
Enable test on Ruby 3.0

### PR DESCRIPTION
**Pull request by voxik**
I am afraid there are some issues on Ruby 3.0, so this might not work right away. Also, not sure about the PPC64

### CODE REVIEW

**Comment by voxik** [comment]
~~~
      tests/models/auto_scaling/configurations_tests.rb
      tried to create Proc object without a block (ArgumentError)
        tests/helpers/succeeds_helper.rb:5:in `new'
        tests/helpers/succeeds_helper.rb:5:in `block in succeeds'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:116:in `test'
        tests/helpers/succeeds_helper.rb:4:in `succeeds'
        tests/helpers/collection_helper.rb:3:in `block in collection_tests'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        tests/helpers/collection_helper.rb:2:in `collection_tests'
        tests/models/auto_scaling/configurations_tests.rb:9:in `block in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        tests/models/auto_scaling/configurations_tests.rb:1:in `<top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
~~~

**Comment by voxik** [comment]
The medicine should be included now.

**Comment by voxik** [comment]
The ppc error is unrelated:

~~~
Gem::RuntimeRequirementNotMetError: zeitwerk requires Ruby version >= 2.4.4. The current ruby version is 2.4.0.
An error occurred while installing zeitwerk (2.4.2), and Bundler cannot continue.
~~~

**Comment by geemus** [comment]
@voxik - thanks for getting a start on this, will try to review/help as I'm able. Hopefully some of this will resolve itself given a little time as things update.

**Comment by geemus** [comment]
Going to close/open this to try and get the tests to retry.

**Review by geemus — APPROVED** [review]
Ok, looks like a bit of time and retrying sorted it out. I'm going to go ahead and bring this in (and hopefully it will work consistently moving forward). @voxik Thanks for the help!

**Comment by voxik** [comment]
BTW there seems to be the same issue in fog-libvirt, so I wonder if the `succeeds` should not be moved into Shindo.

**Comment by geemus** [comment]
@voxik Ah, yes. Probably. That would make sense. I'd welcome a patch if you have a moment, otherwise I can try to get to it in the next few days. Thanks for the tip.

**Pull request merged**
