### PR TITLE
Mock method for AWS S3 post_object_hidden_fields 

### PR DESCRIPTION
**Pull request by byterussian**
Hi,

` post_object_hidden_fields ` doesn't make any external call, can be used as Mock method. Tell me if there a more elegant way to do this instead of copy & paste.

### CODE REVIEW

**Comment by geemus** [comment]
I think in other (similar) cases we have created a little module that has the method in this file. Then you can just "include" that module in to both real/mock and you don't have to copy paste. Does that make sense/work for you?

**Comment by byterussian** [comment]
Yep,

I've just made in this manner. My only doubt is about the doc comment... it goes before the method declaration or inside the `Real` class?

**Comment by geemus** [comment]
Hmm. I guess with the definition probably...

**Comment by geemus** [comment]
Yeah, how you did it seems fine. Thanks!

**Pull request merged**
