### PR TITLE
Fix rubyzip 1.x compatibility.

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by voxik** [comment]
Ah, Ruby 1.8.7 :/

**Comment by lanej** [comment]
Stale.  Closing.

**Comment by geemus** [comment]
Thanks.

**Comment by voxik** [comment]
The patch is still valid and we still carry it around in Fedora, since we have rubyzip 1.x+. I would more appreciate your feedback then closing this issue as a stalled.

**Comment by lanej** [comment]
@voxik Until we drop 1.8 support the best solution would be to modify the 1.8.7 Gemfile to use the 0.9 release of rubyzip.  You'll also need to do some version detection or class aliasing in the lib file.

**Pull request closed without merging**
