### PR TITLE
Add `default_for_az` attribute to subnet

### PR DESCRIPTION
**Pull request by rzaharenkov**
* Add new attribute `default_for_az` to `Subnet` model;
* Update parsers to take into account new attribute;
* Fix comments and tests for `map_public_ip_on_launch` attribute.

### CODE REVIEW

**Comment by geemus** [comment]
LGTM, thanks!

@lanej mind taking a look as well to confirm? Thanks!

**Comment by lanej** [comment]
LGTM (ref: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html).  @rzaharenkov can you rebase off master please?

**Comment by rzaharenkov** [comment]
thanks for review, I've rebased it

**Comment by lanej** [comment]
Thanks @rzaharenkov

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
