### PR TITLE
Add support for AWS Elastic File System

### PR DESCRIPTION
**Pull request by nomadium**
Not ready to merge yet, I'm waiting to receive access to the service preview.

I went ahead and implemented all the requests and mocks according to the API but I need access to the service to verify my code.

Posting it to avoid work duplication if anybody is interested on working on this service.

### CODE REVIEW

**Comment by geemus** [comment]
Sounds like a plan, just let me know if there is anything I can do to help.

**Comment by lanej** [comment]
@nomadium i'm assuming this is done ?

**Comment by nomadium** [comment]
@lanej It's done but I'd prefer to don't merge it yet since I'm don't have access to that service at the present time to do some tests. I'd prefer to wait to have access, although this service remains at beta or preview status, so I don't think is going to be useful for many users at the present time anyway.

You can ping me later to check if I was able to test everything.

**Comment by lanej** [comment]
@nomadium got it.  thanks for the update

**Comment by jpackagejasonc** [comment]
has this PR gotten any further testing now that EFS is GA?

**Comment by nomadium** [comment]
@jpackagejasonc I don't have too much time right now but I'll try to get back to this PR soon with the confirmation if everything is OK or if I need to fix something. Let's see if I can work on it during the next weekend.

**Comment by nomadium** [comment]
Closing it since somebody else implementation was merged.

**Comment by geemus** [comment]
@nomadium thanks for helping us clean this up!

**Pull request closed without merging**
