### PR TITLE
Added a new request - describe_instance_attribute

### PR DESCRIPTION
**Pull request by nilroy**
Added request and parser for DescribeInstanceAttribute API

### CODE REVIEW

**Comment by lanej** [comment]
definitely want to apply a schema format test to make sure it's parsed correctly.

like so https://github.com/fog/fog-aws/blob/master/tests/requests/rds/instance_tests.rb#L32

**Comment by nilroy** [comment]
I am new to this test framework but I can give it a try. Although I tested every attribute manually and checked the parsing is correct. How about implementing the test in https://github.com/fog/fog-aws/blob/master/tests/requests/compute/instance_tests.rb

**Comment by geemus** [comment]
It would be best to stick with shindo for now for tests.

instance_tests would be a good place to add this test.

Adding the mock would be great, but it should be able to run it successfully with non-mock also, so that is  a great place to start (we can always add the mock later).

**Comment by nilroy** [comment]
Thats great :+1: It might take a while for me to understand how the tests works.. Is there anything that you can help me with the starting point? I mean some tricks or docs that will help me understand.

**Comment by geemus** [comment]
Sure. I think you should be able to make something pretty similar to the existing describe_instances test, but just changing the expectations to match with this more closely. Hopefully that gets you somewhat closer, but definitely happy to answer specific questions as needed.

**Comment by nilroy** [comment]
@geemus  - A very basic question - How do I run the tests?

**Comment by geemus** [comment]
`bundle exec shindo path_to_test` where the path can also be a directory with many tests. You may also need to setup some credentials for it, but I think maybe it will prompt you for that part.

**Comment by nilroy** [comment]
@geemus - I tried that and getting below error. It seems I need to require fog somewhere.. Am I missing something?

    Fog::Compute[:aws] | instance requests (aws)
    uninitialized constant Fog::Nullable (NameError)
      /Users/nilanjan1/GIT/fog-aws/tests/requests/compute/instance_tests.rb:6:in `block in <top (required)>'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
      /Users/nilanjan1/GIT/fog-aws/tests/requests/compute/instance_tests.rb:1:in `<top (required)>'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
      /Users/nilanjan1/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'

**Comment by nilroy** [comment]
I got away with the errors after loading FOG and some required libraries in top of the file.

**Comment by nilroy** [comment]
@geemus : Any idea why the travis build failed?

**Comment by nilroy** [comment]
I added the Mock

**Comment by lanej** [comment]
lgtm.

**Comment by nilroy** [comment]
@lanej Sorry for that. I shall try to add some comments to the test to make it more understandable. However I hope the request and parser are understandable. 
@geemus  : what is your point of view?

**Comment by geemus** [comment]
Looks good, thanks!

**Pull request merged**
