### PR TITLE
Added support for EKS Pod Identity.

### LINKED ISSUE #718: Add AWS EKS Pod Identity support
AWS introduced EKS Pod Identity last year: https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/

EKS Pod Identity automatically injects the AWS_CONTAINER_CREDENTIALS_FULL_URI and AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE environment variables into pods. These are supported by AWS SDKs independently of Pod Identity and have been used in ECS for a long time. This mechanism is called Container credential provider: https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

However, if I am understand correctly, https://github.com/fog/fog-aws/blob/master/lib/fog/aws/credential_fetcher.rb is ignoring these environment variables at this moment.

Explanation how EKS Pod Identity works: https://securitylabs.datadoghq.com/articles/eks-pod-identity-deep-dive/

### PR DESCRIPTION
**Pull request by y-sugawara-acs**
I'd like to use EKS Pod Identity with fog-aws, so added support for it.
This will resolve #718.
Could anyone please review my code?

### CODE REVIEW

**Comment by stanhu** [comment]
Looks good to me.

I should note that the AWS Ruby SDK has support for EKS Pod Identity for more than a year, which makes me wonder if this gem should start to use the SDK directly.

@geemus Can you review?

**Review by geemus — APPROVED** [review]

**Comment by geemus** [comment]
I had been wary of trying to put a different interface on top of the SDK and maintain a consistent interface (as well as meaning our performance would be strictly worse), but there are certainly dowsides to the approach we've taken (including things like this).

**Comment by geemus** [comment]
@y-sugawara-acs Thanks!

**Comment by geemus** [comment]
Released in v3.25.0.

**Pull request merged**
