### PR TITLE
Expose S3 pre-signed object delete url

### PR DESCRIPTION
**Pull request by nolith**
This PR allows getting pre-signed URLs for deleting objects.

### CODE REVIEW

**Comment by nolith** [comment]
Hi @geemus 
Do you have an estimate about creating a new release from `master`?
Thank you.

**Comment by geemus** [comment]
Not sure, as it usually isn't me these days.

@lanej any chance you'd be up for a release soon? Thanks!

**Comment by lanej** [comment]
https://rubygems.org/gems/fog-aws/versions/2.0.1

**Comment by geemus** [comment]
Thanks!

**Comment by nolith** [comment]
Thanks to both of you

**Pull request merged**
