### PR TITLE
Rename CDN::AWS to AWS::CDN

### PR DESCRIPTION
**Pull request by jaredbeck**
Fixes fog-core deprecation warning

```
[fog][DEPRECATION] Unable to load Fog::AWS::CDN
[fog][DEPRECATION] The format Fog::CDN::AWS is deprecated
```

Part of https://github.com/fog/fog-aws/issues/466

### CODE REVIEW

**Comment by plribeiro3000** [comment]
👍 from me.

Need someone active on this repo to look and merge tho

**Comment by jaredbeck** [comment]
How should I run tests locally? I couldn't find any docs on it. So, I just pushed and hoped for CI to pass.

**Comment by jaredbeck** [comment]
Also,

> Add a new class that just aliases (and will raise the warning if anybody includes directly).

I don't know how to do a warning. ActiveSupport has `deprecate_constant` but I assumed you don't want that dependency.

**Comment by plribeiro3000** [comment]
I believe you can just overwrite the constructor raising a deprecation notice and call super in the next line.

**Comment by plribeiro3000** [comment]
Yeap, the construction you made is not gonna work.

You will have to open the class and inherit manually then overwrite the method initialize.

If you take a look at the `Fog::Service` module you will see it has a `new` method being defined [here](https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L52-L117)

Sou you can open the class and define it like:

```ruby
class Fog::CDN::AWS < Fog::AWS::CDN
  def self.new(config = {})
    Fog::Logger.deprecation 'Your message here'
    super(config)
  end
end
```

**Comment by jaredbeck** [comment]
> You will have to open the class and inherit manually then overwrite the method initialize.

Done. Thanks.

**Comment by geemus** [comment]
Looks good to me, @plribeiro3000 does that match with what you were asking?

**Pull request merged**
