### PR TITLE
Update kinesis.rb

### PR DESCRIPTION
**Pull request by ioquatix**
Ensure all data access is protected by mutex, and that the mutex is not lazy initialized.

### CODE REVIEW

**Comment by geemus** [comment]
Thanks for the patch. I think I understand why we would want to wrap the data access in the mutex (and not just the sequence number stuff). I'm a little less sure on the lazy init part though. Was that leading to a particular problem? Otherwise, I worry that it would lead to a lot of people now initializing a mutex that wouldn't get used (if they weren't using mocks, and/or weren't using kinesis for example). Does that make sense?

**Comment by ioquatix** [comment]
Yes, it makes sense.

You have two options.

- If you still want to lazy initialize the mutex, you need to use a global mutex to lock around the lazy initialisation which will increase contention.

- Alternatively you could move the code to a different file so it's not loaded in a production environment where it's not needed.

At the end of the day I'm advising you that the code has an issue, and showing you a potential fix. It's up to you to implement what you think makes sense. This was not causing a particular problem. I am just analysing thread safety issues in Ruby code.

**Comment by geemus** [comment]
Thanks for the additional context. I suspect a single, unused mutex won't actually be too much of a problem for users (and it allows us to keep this simple). So I'll bring this in, and we can revisit if/when it becomes needed. Thanks!

**Comment by ioquatix** [comment]
Great!

**Pull request merged**
