### PR TITLE
Drop Ruby<2.0 support

### PR DESCRIPTION
**Pull request by tbrisker**
Users requiring ruby 1.9 or older should use the main fog gem.

### CODE REVIEW

**Comment by geemus** [comment]
@tbrisker I think maybe the main fog gem requires this though, so it would force the dependency change on it as well? (which we should probably do anyway, but that we have so far treated as a breaking change). Does that make sense? Thoughts?

**Comment by tbrisker** [comment]
@geemus do you mean `fog/fog` or `fog/fog-core`? From what I understand from the documentation, `fog/fog` should maintain legacy support while `fog/fog-core` should only support ruby >= 2. I don't mind opening a PR to `fog/fog-core` to clarify this and remove some leftovers there as well.
As far as this gem is concerned, I would say that at least a minor version bump makes sense, if not a major one.

**Comment by plribeiro3000** [comment]
@geemus Some other providers already accepted and merged this change.
I believe it might be okay since we have a version constraint the the gemspec so we wont have any breakeages, old versions of ruby will just not receive more updates. They will be locked in the last current version.

I know this is bad but we need to catch up, we are already 3 versions behind. At some point we wont be able to maintain this train anymore. 😭 

Maybe we should let it go now and if a change is really need for older ruby versions we can backport it.

WDYT?

**Comment by geemus** [comment]
@tbrisker I had meant `fog/fog`. My memory on some of these things can be fuzzy though...

@plribeiro3000 ah. Thanks for the context.

So if I read all that correctly (and please one or both of you correct me if not). We should add a lock to the current version of `fog-aws` to `fog/fog` in addition to this change and then we will be good to go? Or you are saying that the version constraint here will mean that anyone with less than 2.0 will just automatically get the newest version without that constraint? (apologies, I just haven't really made use of the version constraint like this much before).

**Comment by plribeiro3000** [comment]
Yeap. With this constraint, `bundler` wont allow anyone with `ruby` prior to `2.0` to install new versions.

It means that we might get some issues of people using old and perhaps buggy versions of `fog`.
And we have to ask them to move on to ruby `> 2.0` and preferable `2.3`.

**Comment by tbrisker** [comment]
Looks like `fog/fog` itself has actually dropped 1.9 support about 2 years ago in https://github.com/fog/fog/commit/8a413ef54a82e902c59e1e277a38ffe91a466968 - so I think we're good.
And considering that 1.9 is EOL for almost 3 years already, I would say it is reasonable to tell anyone still on it to either use older versions of the fog gem or upgrade to more modern ruby (even 2.1 is already EOL).

**Comment by tbrisker** [comment]
I think perhaps it's time to actually cut a fog 2.0 version that drops support for legacy ruby and lock the 1.x branch on last supporting versions, and only backport serious security fixes to the 1.x branch and relevant gems.

**Comment by plribeiro3000** [comment]
If we are gonna do that, perhaps we should do it for all EOL ruby versions.

**Comment by geemus** [comment]
Bringing this in for now, we can certainly still discuss further changes though. Thanks!

**Pull request merged**
