### PR TITLE
Fix & update aws flavor (provided in GiB) to Megabytes (floor rounded).

### PR DESCRIPTION
**Pull request by xward**
Updated from data available here:
- https://aws.amazon.com/ec2/pricing/on-demand/
- https://aws.amazon.com/ec2/previous-generation/

### CODE REVIEW

**Comment by geemus** [comment]
Oops, looks like this conflicts in some way with the earlier merge actually. Could you look at fixing that? Thanks!

**Comment by xward** [comment]
@geemus I'm on it.

**Comment by xward** [comment]
@geemus done !

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
